# Generated by Django 4.0 on 2021-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مطلب')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن مطلب')),
                ('rate_history', models.JSONField(null=True, verbose_name='امتیاز ها')),
            ],
        ),
    ]
