# Generated by Django 4.0 on 2021-12-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='rate_history',
        ),
        migrations.CreateModel(
            name='RateDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(max_length=5, null=True, verbose_name='امتیاز')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.documents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
