# Generated by Django 4.0 on 2021-12-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_remove_documents_rate_history_ratedocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedocuments',
            name='rate',
            field=models.PositiveIntegerField(null=True, verbose_name='امتیاز'),
        ),
    ]
