# Generated by Django 4.0 on 2021-12-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_ratedocuments_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedocuments',
            name='rate2',
            field=models.IntegerField(default=1),
        ),
    ]