# Generated by Django 4.0 on 2021-12-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_remove_ratedocuments_rate2'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='rate_history',
            field=models.JSONField(default={}, verbose_name='امتیاز ها'),
        ),
    ]
