# Generated by Django 4.0 on 2021-12-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_documents_rate_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='rate_history',
            field=models.JSONField(verbose_name='امتیاز ها'),
        ),
    ]
