# Generated by Django 4.0 on 2021-12-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_ratedocuments_rate2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratedocuments',
            name='rate2',
        ),
    ]
