# Generated by Django 4.0 on 2021-12-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_remove_ratedocuments_rate2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='rate_history',
        ),
    ]
